language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
install:
  - "pip install nikola"
  - "pip install flake8 --use-mirrors"
script:
  - nosetests --with-doctest --doctest-options=+NORMALIZE_WHITESPACE
  - "flake8 --ignore=E501 ."
