before_install:
  - "if [[ $NMODE == 'nikola' ]]; then sudo apt-get update -qq || true; fi"
  - "if [[ $NMODE == 'nikola' ]]; then sudo apt-get install enchant; fi"
language: python
cache: apt
python:
  - "2.6"
  - "2.7"
  - "3.3"
matrix:
  include:
    - python: "2.7"
      env: NMODE=flake8
env:
    NMODE=nikola
install:
  - "if [[ $NMODE == 'nikola' ]]; then wget https://github.com/getnikola/wheelhouse/archive/$(scripts/getpyver.py).zip; fi"
  - "if [[ $NMODE == 'nikola' ]]; then unzip $(scripts/getpyver.py).zip; fi"
  - "if [[ $NMODE == 'nikola' ]]; then pip install --use-wheel --no-index --find-links=wheelhouse-$(scripts/getpyver.py short) lxml Pillow; fi"
  - "if [[ $NMODE == 'nikola' ]]; then pip install nikola --use-mirrors; fi"
  - "if [[ $NMODE == 'nikola' ]]; then find plugins/*/ | grep 'requirements.txt' | xargs cat | xargs pip install && true; fi"
  - "if [[ $NMODE == 'flake8' ]]; then pip install flake8 --use-mirrors; fi"
script:
  - "if [[ $NMODE == 'nikola' ]]; then nosetests --with-doctest --doctest-options=+NORMALIZE_WHITESPACE --logging-filter=-yapsy; fi"
  - "if [[ $NMODE == 'flake8' ]]; then flake8 --ignore=E501 .; fi"
notifications:
  irc:
    channels:
      - "chat.freenode.net#nikola"
    template:
      - "[PLUGINS] %{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "[PLUGINS] Change view: %{compare_url}"
      - "[PLUGINS] Build details: %{build_url}"
