name: Nikola Plugins CI
on:
  # Run on all pushes to master (including merge of PR)
  push:
    branches: master
  # Run on all changes in pull requests
  pull_request:

jobs:
  nikola:
    name: Nikola plugin tests (Python ${{ matrix.python }} on ${{ matrix.image }})
    strategy:
      fail-fast: false
      matrix:
        python: [3.5, 3.6, 3.7, 3.8, 3.9]
        image:
          - ubuntu-latest
    runs-on: '${{ matrix.image }}'
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '${{ matrix.python }}'
      - name: Upgrade packaging stack, install pytest and requests
        run: |
          pip install --upgrade-strategy eager -U pip setuptools wheel pytest requests
      - name: Install Nikola
        run: |
          pip install git+https://github.com/getnikola/nikola.git#egg=Nikola
      - name: Install test dependencies
        run: |
          pip install pybtex
      - name: Setup Java
        uses: actions/setup-java@v2.2.0
        with:
          java-version: 11
          distribution: 'temurin'
      - name: Install PlantUML
        env:
          PLANTUML_VERSION: 1.2020.24
        run: |
          # Not using "apt-get install plantuml" because it's usually an old version
          wget -q -O "${{github.workspace}}/plantuml.jar" "https://repo1.maven.org/maven2/net/sourceforge/plantuml/plantuml/${PLANTUML_VERSION}/plantuml-${PLANTUML_VERSION}.jar"
      - name: Run tests
        env:
          PLANTUML_EXEC: java -Djava.awt.headless=true -jar ${{github.workspace}}/plantuml.jar
        run: |
          py.test --color=yes tests/
  site:
    name: plugins.getnikola.com site build
    strategy:
      fail-fast: false
      matrix:
        python: [3.9]
        image:
          - ubuntu-latest
    runs-on: '${{ matrix.image }}'
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '${{ matrix.python }}'
      - name: Upgrade packaging stack
        run: |
          pip install --upgrade-strategy eager -U pip setuptools wheel
      - name: Install Nikola
        run: |
          pip install git+https://github.com/getnikola/nikola.git#egg=Nikola[extras]
      - name: Build site
        env:
          NIKOLA_SHOW_TRACEBACKS: 1
          NIKOLA_PLUGINS_LOCAL_BUILD: 1
        working-directory: site
        run: |
          nikola build -v 2
  flake8:
    name: Linting (flake8)
    strategy:
      matrix:
        python:
          - 3.9
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '${{ matrix.python }}'
      - name: Install requirements
        run: |
          pip install flake8
      - name: Run flake8
        run: |
          flake8 v*/
